import type { SharePointVerticalConfigItemDto } from "../contracts/SharePointVerticalConfigItemDto";

export const sampleSharePointConfigItems: SharePointVerticalConfigItemDto[] = [
  {
    AggregateParticipation: false,
    DefaultVertical: true,
    Enabled: true,
    Key: "all",
    Kind: "synthetic-aggregate",
    ResultType: "document",
    SortOrder: 0,
    SupportsViewMore: false,
    TemplateKey: "synthetic-aggregate",
    Title: "All"
  },
  {
    AggregateParticipation: true,
    Enabled: true,
    EntityTypes: "listItem,sitePage",
    FieldSelection: "title,summary,sourceLabel,modifiedTime",
    Key: "it-hr-colleague-direct",
    Kind: "standard",
    LayoutRegion: "main",
    RenderingHint: "document-list",
    ResultType: "document",
    SectionAccentTone: "brand",
    ScopeType: "tenant",
    SortOrder: 1,
    SummarySize: 4,
    DedicatedSize: 10,
    SupportsViewMore: true,
    TemplateKey: "knowledge",
    Title: "IT, HR, and Colleague Direct"
  },
  {
    AggregateParticipation: true,
    Enabled: true,
    EntityTypes: "event,listItem",
    FieldSelection: "title,summary,date,location,path,thumbnailUrl",
    Key: "sites-events",
    Kind: "standard",
    LayoutRegion: "main",
    RenderingHint: "event-list",
    ResultType: "event",
    SectionAccentTone: "warning",
    ScopeType: "sites",
    SiteIds: "events-site,connections-site",
    SortOrder: 2,
    SummarySize: 3,
    DedicatedSize: 8,
    SupportsViewMore: true,
    TemplateKey: "events-sites",
    Title: "Sites and events"
  },
  {
    AggregateParticipation: true,
    Enabled: true,
    EntityTypes: "listItem",
    FieldSelection: "title,summary,date,path,thumbnailUrl",
    Key: "news",
    Kind: "standard",
    LayoutRegion: "main",
    RenderingHint: "news-list",
    ResultType: "news",
    SectionAccentTone: "danger",
    ScopeType: "tenant",
    SortOrder: 3,
    SummarySize: 3,
    DedicatedSize: 8,
    SupportsViewMore: true,
    TemplateKey: "news",
    Title: "News"
  },
  {
    AggregateParticipation: true,
    Enabled: true,
    EntityTypes: "person",
    FieldSelection: "displayName,jobTitle,officeLocation,photoUrl",
    Key: "people",
    Kind: "standard",
    LayoutRegion: "side",
    RenderingHint: "people-list",
    ResultType: "person",
    SectionAccentTone: "success",
    ScopeType: "tenant",
    SortOrder: 4,
    SummarySize: 4,
    DedicatedSize: 12,
    SupportsViewMore: true,
    TemplateKey: "people",
    Title: "People"
  },
  {
    AggregateParticipation: true,
    Enabled: true,
    EntityTypes: "externalItem",
    FieldSelection: "title,summary,tileLabel",
    Key: "resources",
    Kind: "standard",
    LayoutRegion: "side",
    RenderingHint: "resource-grid",
    ResultType: "resource",
    SectionAccentTone: "info",
    ScopeType: "custom",
    SortOrder: 5,
    SummarySize: 6,
    DedicatedSize: 12,
    SupportsViewMore: true,
    TemplateKey: "resources",
    Title: "Resources"
  },
  {
    AggregateParticipation: true,
    Enabled: true,
    EntityTypes: "driveItem",
    FieldSelection: "title,summary,owner,extension,modifiedTime",
    Key: "files",
    Kind: "standard",
    LayoutRegion: "side",
    RenderingHint: "file-list",
    ResultType: "file",
    SectionAccentTone: "neutral",
    ScopeType: "tenant",
    SortOrder: 6,
    SummarySize: 4,
    DedicatedSize: 12,
    SupportsInfiniteScroll: true,
    SupportsViewMore: true,
    TemplateKey: "files",
    Title: "Files"
  }
];
