export type SharePointVerticalConfigItemDto = {
  AggregateParticipation?: boolean | string;
  DataSourceKey?: string;
  DedicatedSize?: number | string;
  DefaultVertical?: boolean | string;
  Enabled?: boolean | string;
  EntityTypes?: string;
  ExtraFilters?: string;
  FieldSelection?: string;
  IconName?: string;
  Id?: number;
  Key?: string;
  Kind?: string;
  LayoutRegion?: string;
  RenderingHint?: string;
  ResultType?: string;
  ScopeType?: string;
  SectionAccentTone?: string;
  SiteIds?: string;
  SortOrder?: number | string;
  SortKeys?: string;
  SummarySize?: number | string;
  SupportsInfiniteScroll?: boolean | string;
  SupportsRefiners?: boolean | string;
  SupportsViewMore?: boolean | string;
  TemplateKey?: string;
  Title?: string;
  ViewMoreTargetKey?: string;
};
