storage: ../../.local/verdaccio/storage

auth:
  htpasswd:
    file: ../../.local/verdaccio/htpasswd
    max_users: 1000

packages:
  "@functions-oneui/*":
    access: $all
    publish: $authenticated
    unpublish: $authenticated
  "**":
    access: $all

security:
  api:
    legacy: true

server:
  keepAliveTimeout: 60

log:
  - { type: stdout, format: pretty, level: http }
